apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentiment-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: sentiment.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: sentiment-analysis
                port:
                  number: 80
