apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-service
  namespace: default
  labels:
    app: sentiment-analysis
spec:
  selector:
    app: sentiment-analysis
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
